//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryRecio_Lab3IEFI.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pryRecio_Lab3IEFI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_1 {
            get {
                object obj = ResourceManager.GetObject("Prototipo_de_Ordenador_Inicio_Sesión_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul {
            get {
                object obj = ResourceManager.GetObject("Prototipo de Ordenador Inicio Sesión Web Ilustrado Ordenado Azul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul__1_ {
            get {
                object obj = ResourceManager.GetObject("Prototipo de Ordenador Inicio Sesión Web Ilustrado Ordenado Azul (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul__1_1 {
            get {
                object obj = ResourceManager.GetObject("Prototipo de Ordenador Inicio Sesión Web Ilustrado Ordenado Azul (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul__2_ {
            get {
                object obj = ResourceManager.GetObject("Prototipo de Ordenador Inicio Sesión Web Ilustrado Ordenado Azul (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul-removebg-preview" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("Prototipo_de_Ordenador_Inicio_Sesión_Web_Ilustrado_Ordenado_Azul-removebg-preview" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2025_05_28_at_10_29_30_AM {
            get {
                object obj = ResourceManager.GetObject("WhatsApp_Image_2025_05_28_at_10_29_30_AM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
